
class AverageWordLength:

    # Any one-time initialization code can go here.  There entire nested question-and-answer
    # dataset is passed as a parameter, in case the initialization requires any of that data.

    def init(self, allQuestions):
        return

    # Given a specific question, return a feature vector (one-dimensional array of one
    # or more features.

    def createFeatureVector(self, question, parentQuestion):
        sum = 0
        count = 0
        for word in question['question_words_nostopwords']:
            sum += len(word)
            count += 1
        if count == 0:
            return [0]
        else:
            return [sum/count]

    # Returns a list of names for the features generated by this module.  Each entry in the
    # list should correspond to a feature in the createFeatureVector() response.

    def getFeatureNames(self):
        return ['avg-word-len']