import nltk
from nltk import *

class NER:

    # Any one-time initialization code can go here.  There entire nested question-and-answer
    # dataset is passed as a parameter, in case the initialization requires any of that data.

    def init(self, allQuestions):
        return

    # Given a specific question, return a feature vector (one-dimensional array of one
    # or more features.
    def createFeatureVector(self, question, parentQuestion):
        # This is just placeholder code - insert code that actually generates a feature vector here
        # for the given question, and then return that feature vector instead of [0].
        # question['namedEntities']=nltk.ne_chunk(question['question_words_pos_nostopwords']);
        # nltk.pprint(question['namedEntities'])
        return [0]

    # Returns a list of names for the features generated by this module.  Each entry in the
    # list should correspond to a feature in the createFeatureVector() response.

    def getFeatureNames(self):
        return ['NER']