
class CommonBiGrams:

    # Any one-time initialization code can go here.  There entire nested question-and-answer
    # dataset is passed as a parameter, in case the initialization requires any of that data.

    def init(self, allQuestions):
        return

    # Given a specific question, return a feature vector (one-dimensional array of one
    # or more features.

    def createFeatureVector(self, question, parentQuestion):
        matches = 0
        for questionBigram in question['question_bigram_list']:
            for parentBigram in parentQuestion['question_bigram_list']:
                if questionBigram == parentBigram:
                    matches += 1
        return [matches]

    # Returns a list of names for the features generated by this module.  Each entry in the
    # list should correspond to a feature in the createFeatureVector() response.

    def getFeatureNames(self):
        return ['common-bigrams']